### PR TITLE
0.2/699 cc print preference

### PR DESCRIPTION
**Pull request by katjam**
Started tests. Will finish in: 0.2/699-cc-print-pref-tests

Thought best to get this in for @charlesstrange2 to merge with his #668

### CODE REVIEW

**Review by charlesstrange2 — APPROVED** [review]
Okedoke :shipit:
Except it toattly failed a test. drat.

**Comment by katjam** [comment]
https://trello.com/c/Dhy7qgJn/699-set-printing-preference-for-each-cc-individual-collections-sheets-or-all-families-collection-sheet

**Comment by katjam** [comment]
@charlesstrange2 My bad... typo. I will fix.

**Comment by charlesstrange2** [comment]
Hey, only travis spotted it...

**Pull request merged**
