### PR TITLE
0.2/733 new style search page

### PR DESCRIPTION
**Pull request by alexalala**
https://trello.com/c/QckZUC1C/733-new-style-search-page

Added the extra div (@else
        	<div class="right"></div>
                @endif) as it was the best way to centre the header at all times.
🐟

### CODE REVIEW

**Comment by charlesstrange2** [comment]
Travis teckons the tests are failing. Have a look at the log and see if your changes need to be reflected in the tests.

**Review by charlesstrange2 — CHANGES_REQUESTED** [review]
Travis thinks the tests are failing.

**Comment by alexalala** [comment]
@charlesstrange2 dumdum error that took me way too long to figure out hahah! Ready to re-check now though

**Review by charlesstrange2 — APPROVED** [review]
Cool
🚢 🇮🇹

**Pull request merged**
