### PR TITLE
0.1/604 options screen menu html

### PR DESCRIPTION
**Pull request by alexalala**
Wasn't sure whether the whole fontawesome folder is necessary, but it is needed for browser support apparently.

🐔

### CODE REVIEW

**Review by charlesstrange2 — CHANGES_REQUESTED** [review]
Do we need the less and scss files? we're not recompiling anything right now...

**Comment by alexalala** [comment]
Deffo not for now, but may want to use sass in the future. Shall I get rid? 😄

**Comment by alexalala** [comment]
@charlesstrange2 will remove the unnecessaries for now! Can always add back in if anything looks broken

**Comment by charlesstrange2** [comment]
Hmm. No, we're still fluid, so the flexibility is more useful than the size issue. 
besides, I bet there's a cunning way to include it in a "clever fashion", later on...

**Review by charlesstrange2 — APPROVED** [review]

**Comment by charlesstrange2** [comment]
Also, it'll all get mixed up when we blade it.

**Comment by alexalala** [comment]
@charlesstrange2 ok will merge as is haha!

**Pull request merged**
