### PR TITLE
0.2/735 new style edit page

### PR DESCRIPTION
**Pull request by alexalala**
Again includes commits from previous PR

https://trello.com/c/giNFA4da/735-new-style-edit-page

🏷

### CODE REVIEW

**Comment by charlesstrange2** [comment]
Test itShowsAListOfChildren is unhappy because it can't see "eligible".

**Comment by alexalala** [comment]
@charlesstrange2 when you get a chance can you re-review the two page tickets pls :D will need their changes in my next ticket

**Review by charlesstrange2 — CHANGES_REQUESTED** [review]
As discussed, centre of text gets a bit squiff on windows resize and there's a light green border round the header for the summary column.

**Review by charlesstrange2 — APPROVED** [review]

**Comment by alexalala** [comment]
@charlesstrange2 fixeded

**Pull request merged**
