### PR TITLE
updated as per Johnathans request

### PR DESCRIPTION
**Pull request by alexalala**
updated year and copy as per Johnathans comment on:

https://trello.com/c/nl6Yh3Cn/75-copyright-statements-and-license-terms

⛱

### CODE REVIEW

**Review by charlesstrange2 — APPROVED** [review]
Yup, I don't recall putting it elsewhere in Store. :shipit:

**Comment by alexalala** [comment]
Oooh, just noticed his comment wants "All Rights Reserved' in caps.. do you think this fits ok with the rest of the copy @charlesstrange2 ?

**Comment by charlesstrange2** [comment]
Ah. No. it might not fit, but Lawyers have signed off on it, so make it that, and we'll proke him on Tuesday about it.

**Comment by alexalala** [comment]
@charlesstrange2 will just merge for now as it makes more grammatical sense this way.

**Pull request merged**
